[project]
name = "nativdata-project2-nigeria-ncd-geospatial-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "folium>=0.20.0",
    "geopandas>=1.1.4",
    "matplotlib>=3.11.2",
    "pandas>=3.0.6",
    "seaborn>=0.13.2",
]
